SELECT IF(MONTH(E.DIFFERENTIATION_DATE)<=3, '1Q', IF(MONTH(E.DIFFERENTIATION_DATE)<=6, '2Q', IF(MONTH(E.DIFFERENTIATION_DATE)<=9, '3Q', '4Q'))) QUARTER, COUNT(ID) ECOLI_COUNT
FROM ECOLI_DATA E
GROUP BY QUARTER
ORDER BY QUARTER;
