SELECT YEAR(E.DIFFERENTIATION_DATE) YEAR, (SELECT MAX(E2.SIZE_OF_COLONY) FROM ECOLI_DATA E2 WHERE YEAR(E.DIFFERENTIATION_DATE) = YEAR(E2.DIFFERENTIATION_DATE))-E.SIZE_OF_COLONY YEAR_DEV, E. ID
FROM ECOLI_DATA E
ORDER BY 1, 2;
