# SELECT *
# FROM HR_DEPARTMENT D JOIN HR EMPLOYEES E
# ON D.DEPT_ID = E.DEPT_ID
# WHERE E.EMP_NO = (SELECT EMP_NO
#                     FROM HR_GRADE
#                     GROUP BY EMP_NO
#                     ORDER BY SUM(SCORE) DESC
#                     LIMIT 1);

SELECT SUM(SCORE) SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1;