SELECT COUNT(F.ID) FISH_COUNT, MAX(F.LENGTH) MAX_LENGTH, F.FISH_TYPE
FROM FISH_INFO F
WHERE F.FISH_TYPE IN (SELECT F2.FISH_TYPE
                FROM FISH_INFO F2
                GROUP BY F2.FISH_TYPE
                HAVING AVG(IFNULL(F2.LENGTH, 10))>=33)
GROUP BY F.FISH_TYPE
ORDER BY F.FISH_TYPE;